spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:test;MODE=MYSQL"
    password: 1234
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true